"""empty message

Revision ID: 175ed7212028
Revises: f99a88347be5
Create Date: 2024-07-19 19:32:48.744757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175ed7212028'
down_revision = 'f99a88347be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('eventos_relacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('objetivo_relacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('objetivo_relacion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('eventos_relacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
