"""empty message

Revision ID: 4c3fb359784c
Revises: ffc75c14db14
Create Date: 2024-07-26 19:49:59.906847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3fb359784c'
down_revision = 'ffc75c14db14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('foto_peril_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_peril_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('foto_perfil_url')

    # ### end Alembic commands ###
