"""empty message

Revision ID: 9ddcb37c1aaa
Revises: 175ed7212028
Create Date: 2024-07-19 20:00:00.935867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddcb37c1aaa'
down_revision = '175ed7212028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas_programadas', schema=None) as batch_op:
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas_programadas', schema=None) as batch_op:
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
