"""empty message

Revision ID: bb9b7d40c85d
Revises: 
Create Date: 2024-08-07 17:16:46.459926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9b7d40c85d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuarios_relacion', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'usuarios', ['usuarios_relacion'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_url')

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('usuarios_relacion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuarios_relacion')

    # ### end Alembic commands ###
